title: "The Ecma Natives "
description: >-
  A simple site with labs used by lamplighters from the global code programme.
baseurl: "/"
url: "https://localhost:4000"

header_pages:
  - index.md
  - about.md

style: light

footer: '<h1><a href="/ecmanatives">Ecma Natives Labs</a></h1>More from Peter over at <a href="http://picoreclame.nl">Picoreclame</a><br> more about the summer programme at <a href="https://globalcode.org.uk/">Global Code</a>'

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-feed

host: 0.0.0.0
port: 4000
